spring:
  application:
    auth_server_url:  http://dev-auth.dr-elephant.net:8050
  datasource:
    url: jdbc:mysql://rm-uf6q4j0blzb8y2r4nbo.mysql.rds.aliyuncs.com:3306/dev_drelephant?useSSL=false
    username: devadmin
    password: dev@Ms123
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall,log4j2
      initialSize: 10
      minIdle: 1
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'drelephant'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        resetEnable: true
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://dev-eureka1.dr-elephant.net:8861/eureka/,http://dev-eureka2.dr-elephant.net:8862/eureka/

